version: "3"

services:

  nginx:
    build:
      context: . 
      dockerfile: nginx/Dockerfile
    ports:
      - "8080:80"
    volumes:
      - .:/app/
      - ./www:/var/www
    links:
      - php

  php:
    build:
      context: .
      dockerfile: php/Dockerfile
    volumes:
      - .:/app/
      - ./www:/var/www
